### PR TITLE
Add plural helpers

### PR DESCRIPTION
**Pull request by sean-**
Useful in hashicorp/consul#3037 and hashicorp/consul#2217

```
$ sockaddr eval GetPrivateIPs
10.12.24.232 10.34.0.187
```

### CODE REVIEW

**Comment by sean-** [comment]
Ping @slackpad .  It'd be nice if these PRs can get merged so we can also PR support into `gomplate` (see hairyhenderson/gomplate#145).

**Comment by slackpad** [comment]
Sorry I just got back into town but I'll try to take a look at these asap.

**Comment by sean-** [comment]
No worries, I just wanted to bump the issue since I figured you were buried after traveling.

**Comment by slackpad** [comment]
@sean - wanna rebase this one and then we will get this in?

**Comment by slackpad** [comment]
@sean- want to rebase this one and we will get it in? The other changes ahead of this have been merged.

**Comment by sean-** [comment]
@slackpad Done.  Thank you!

**Pull request merged**
